### ISSUE TITLE
Confusion in Validation generator 

### ISSUE THREAD

**Issue by ReemFida** [drkhan107/CoroNet#2]
Hi there,
I have been trying to execute your code. In the code, you have used the training dataset directory in valid batches, correct me if I am wrong, are we not suppose to use test data directory in valid batches?

**Comment by drkhan107** [comment]
I have used data generators which splits the data itself based on the
parameter called 'validation_split'. So you dont need to have a saperate
directory for validation images.

Thanks and Regards
Dr. Asif Iqbal Khan

**Comment by ReemFida** [comment]
Thanks for your reply
